### ISSUE TITLE
Enforce PEP-8 style guide

### ISSUE THREAD

**Issue by kadler** [IBM/python-itoolkit#19]
Code should be cleaned up to use PEP-8 guidelines.

**Comment by PK1210** [comment]
I would like to help you with this

**Comment by kadler** [comment]
Any PRs are welcome. Please check out CONTRIBUTING.md first.

**Comment by ThePrez** [comment]
Thanks, @PK1210! I look forward to your contributions!

**Comment by cclauss** [comment]
You can do this in an automated way.  Run a tool(s) like [autopep8](https://github.com/hhatto/autopep8), [yapf](https://github.com/google/yapf), [black](https://github.com/ambv/black), [isort](https://github.com/timothycrosley/isort).  My person preference is __black__ because you can't mess with it. _Any color you want as long as it is __black___.

**Comment by kadler** [comment]
Sorry @PK1210, but I have some changes I wanted to make and since major cleanups like this are pretty noisy, I wanted to get this done first. If you are still looking to contribute, there are more issues with the [good first issue](https://github.com/IBM/python-itoolkit/labels/good%20first%20issue) tag
