### ISSUE TITLE
State full XMLSERVICE calls

### ISSUE THREAD

**Issue by deliego** [IBM/python-itoolkit#30]
Reading up online how to make use of state full XMLSERVICE calls for faster response and simulate an open recurring job (as if I was using the 5250 terminal window), this is the route I would like to go. Especially since I would be able to gather data based on an "elapsed time" as well. For example, I could run "wrkdsksts" and get read/writes/reqs about disks since the time the job was first run, or maybe "dspsyssts" and get CPU over a period of time. Without this, I would only get data at the time the job was executed and it would be a snapshot at that time, not over a period of time.

My question is, using ipc and ctl parameters during the transport definition of idb2call, is this possible? Does the call to the stored procedure end the job or will it leave it open to re-use if I were to call it again?

I'm trying to follow the examples here (It's PHP, but at least gives me an idea of what's capable):
http://yips.idevcloud.com/wiki/index.php/XMLService/XMLSERVICEConnect
http://yips.idevcloud.com/wiki/index.php/XMLService/XMLSERVICEConfig

Thanks!

**Comment by kadler** [comment]
Yes, using the ipc and ctl keywords, it is possible to run stateful. This is the same regardless of the transport. Running stateful is quite an advanced technique and requires quite a deal of understanding about how XMLSERVICE works. When you use ctl='*here', XMLSERVICE runs your requested actions from the job in which you called XMLSERVICE (for idb2call, this is a QSQSRVR job). When you use ctl='*sbmjob', XMLSERVICE submits a new job and associates that with the ipc key specified. That job stays running until explicitly shut down (I think you can set a timeout somehow).

Running stateful and calling CL commands won't be of any use however, due to the way XMLSERVICE calls CL commands. It does so by calling through the PASE `system` command, which means a new job is spawned to call the CL command, regardless of statefulness.

**Comment by deliego** [comment]
Ohh i'm learning :-). Thanks for the prompt input, much appreciated!

**Comment by kadler** [comment]
Also, as long as you keep the database connection open, you can make repeated calls to XMLSERVICE through it using ctl='*here' and everything *should* be stateful. You only need stateful XMLSERVICE when you use the REST transport or when you're using it from a web application *and* need statefulness across multiple requests.
