### ISSUE TITLE
Drop Python 3.4 Support

### ISSUE THREAD

**Issue by kadler** [IBM/python-itoolkit#57]
Like #56, but for Python 3.4. Python 3.4 went EOL over a year ago and Python 3.4 in OPS went EOL at the same time or at least by the end of 2019. I think we should time this with 2.0 as well, considering the usage of OPS and the fact that we still need to support 2.7.

**Comment by kadler** [comment]
As Python 3.5 will go EOL in September, it may make sense to drop support for it at the same time.

**Comment by jkyeung** [comment]
I guess it depends on when you are expecting to get around to itoolkit 2.0. If it's soonish, I'd be a little worried about stranding people who are stuck with Python 3.4 or 3.5 on their Windows or Linux machine. I guess if they really can't change their Python, they'll just have to live with not changing their itoolkit either. But it certainly would be nice if they could still update itoolkit freely.

(I do not have the same sympathy for folks on Python 2.)

Is there something specific that you are eager to clean up by dropping Python 3.4 (and 3.5) compatibility? Off the top of my head, my guess is you'd like to start using f-strings (because that would be my reason).

**Comment by kadler** [comment]
f-strings would be great for sure, though it's not that big of a deal. I see quite a few projects dropping Python 3.4 support and Poetry has already dropped it for version 1.1.

I don't foresee having a 2.0 out anytime soon. Regardless, depending on the timeframe we could maintain 1.x in bugfix mode only if it's needed.

**Comment by kadler** [comment]
Closed by 6be3983721723f8100f170651ba74e32116c4dcd
